export const baseAlphabet = [{word: 'a', desc: '에이'}, {word: 'b', desc: '비'}, {word: 'c', desc: '시'},
  {word: 'd', desc: '디'}, {word: 'e', desc: '이'}, {word: 'f', desc: '에프'},
  {word: 'g', desc: '지'}, {word: 'h', desc: '에이치'}, {word: 'i', desc: '아이'},
  {word: 'j', desc: '제이'}, {word: 'k', desc: '케이'}, {word: 'l', desc: '엘'},
  {word: 'm', desc: '엠'}, {word: 'n', desc: '엔'}, {word: 'o', desc: '오'},
  {word: 'p', desc: '피'}, {word: 'q', desc: '큐'}, {word: 'r', desc: '알'},
  {word: 's', desc: '에스'}, {word: 't', desc: '티'}, {word: 'u', desc: '유'},
  {word: 'v', desc: '브이'}, {word: 'w', desc: '더블유'}, {word: 'x', desc: '엑스'},
  {word: 'y', desc: '와이'}, {word: 'z', desc: '지'}];
export const baseAlphabetUpper = [{word: 'A', desc: '에이'}, {word: 'B', desc: '비'}, {word: 'C', desc: '시'},
  {word: 'D', desc: '디'}, {word: 'E', desc: '이'}, {word: 'F', desc: '에프'},
  {word: 'G', desc: '지'}, {word: 'H', desc: '에이치'}, {word: 'I', desc: '아이'},
  {word: 'J', desc: '제이'}, {word: 'K', desc: '케이'}, {word: 'L', desc: '엘'},
  {word: 'M', desc: '엠'}, {word: 'N', desc: '엔'}, {word: 'O', desc: '오'},
  {word: 'P', desc: '피'}, {word: 'Q', desc: '큐'}, {word: 'R', desc: '알'},
  {word: 'S', desc: '에스'}, {word: 'T', desc: '티'}, {word: 'U', desc: '유'},
  {word: 'V', desc: '브이'}, {word: 'W', desc: '더블유'}, {word: 'X', desc: '엑스'},
  {word: 'Y', desc: '와이'}, {word: 'Z', desc: '지'}];
export const baseAlphabetLowerUpper = [{word: 'a', desc: '에이'}, {word: 'b', desc: '비'}, {word: 'c', desc: '시'},
  {word: 'd', desc: '디'}, {word: 'e', desc: '이'}, {word: 'f', desc: '에프'},
  {word: 'g', desc: '지'}, {word: 'h', desc: '에이치'}, {word: 'i', desc: '아이'},
  {word: 'j', desc: '제이'}, {word: 'k', desc: '케이'}, {word: 'l', desc: '엘'},
  {word: 'm', desc: '엠'}, {word: 'n', desc: '엔'}, {word: 'o', desc: '오'},
  {word: 'p', desc: '피'}, {word: 'q', desc: '큐'}, {word: 'r', desc: '알'},
  {word: 's', desc: '에스'}, {word: 't', desc: '티'}, {word: 'u', desc: '유'},
  {word: 'v', desc: '브이'}, {word: 'w', desc: '더블유'}, {word: 'x', desc: '엑스'},
  {word: 'y', desc: '와이'}, {word: 'z', desc: '지'},
  {word: 'A', desc: '에이'}, {word: 'B', desc: '비'}, {word: 'C', desc: '시'},
  {word: 'D', desc: '디'}, {word: 'E', desc: '이'}, {word: 'F', desc: '에프'},
  {word: 'G', desc: '지'}, {word: 'H', desc: '에이치'}, {word: 'I', desc: '아이'},
  {word: 'J', desc: '제이'}, {word: 'K', desc: '케이'}, {word: 'L', desc: '엘'},
  {word: 'M', desc: '엠'}, {word: 'N', desc: '엔'}, {word: 'O', desc: '오'},
  {word: 'P', desc: '피'}, {word: 'Q', desc: '큐'}, {word: 'R', desc: '알'},
  {word: 'S', desc: '에스'}, {word: 'T', desc: '티'}, {word: 'U', desc: '유'},
  {word: 'V', desc: '브이'}, {word: 'W', desc: '더블유'}, {word: 'X', desc: '엑스'},
  {word: 'Y', desc: '와이'}, {word: 'Z', desc: '지'}
];

export const baseWord = [{word: 'apple', desc: '사과', desc2: '애플'}, {word: 'banana', desc: '바나나', desc2: '바나나'}, {word: 'grape', desc: '포도', desc2: '그레이프'},
  {word: 'love', desc: '사랑', desc2: '러브'}, {word: 'flower', desc: '꽃', desc2: '플라워'}, {word: 'cookie', desc: '쿠키', desc2: '쿠키'},
  {word: 'tiger', desc: '호랑이', desc2: '타이거'},{word: 'doctor', desc: '의사', desc2: '닥터'}, {word: 'sea', desc: '바다', desc2: '시'},
  {word: 'summer', desc: '여름', desc2: '섬머'}, {word: 'fall', desc: '가을', desc2: '퍼얼'},
  {word: 'winter', desc: '겨울', desc2: '윈터'}, {word: 'spring', desc: '봄', desc2: '스프링'},
  {word: 'name', desc: '이름', desc2: '네임'}, {word: 'listen', desc: '듣다', desc2: '리슨'},
  {word: 'speak', desc: '말하다', desc2: '스피크'}, {word: 'you', desc: '너, 당신', desc2: '유'}, {word: 'internet', desc: '인터넷', desc2: '인터넷'},
  {word: 'coding', desc: '코딩', desc2: '코딩'}, {word: 'study', desc: '공부', desc2: '스터디'},
  {word: 'city', desc: '도시', desc2: '시티'},  {word: 'number', desc: '수', desc2: '넘버'}, {word: 'print', desc: '쓰다', desc2: '프린트'},
  {word: 'family', desc: '가족', desc2: '패밀리'}, {word: 'sound', desc: '소리', desc2: '사운드'},
  {word: 'mother', desc: '엄마', desc2: '마덜'}, {word: 'father', desc: '아빠', desc2: '파덜'},{word: 'ant', desc: '개미', desc2: '앤트'},
  {word: 'bear', desc: '곰', desc2: '베어'},{word: 'cat', desc: '고양이', desc2: '캣'},{word: 'dog', desc: '강아 지', desc2: '도그'},{word: 'cow', desc: '소', desc2: '카우'},
  {word: 'fox', desc: '여우', desc2: '폭스'},{word: 'frog', desc: '개구리', desc2: '프로그'},{word: 'horse', desc: '소', desc2: '홀스'},{word: 'mouse', desc: '쥐', desc2: '마우스'},
  {word: 'pig', desc: '돼지', desc2: '피그'},{word: 'rabbit', desc: '토끼', desc2: '래빗'},{word: 'zebra', desc: '얼룩말', desc2: '지브라'},{word: 'zoo', desc: '동물원', desc2: '주'},
  {word: 'elephant', desc: '코끼리', desc2: '엘리펀트'},{word: 'goat', desc: '염소', desc2: '고트'},{word: 'duck', desc: '오리', desc2: '덕'},
  {word: 'egg', desc: '달걀', desc2: '에그'},{word: 'pool', desc: '웅덩이', desc2: '풀'},{word: 'stone', desc: '돌', desc2: '스톤'},
  {word: 'lion', desc: '사자', desc2: '라이언'},{word: 'television', desc: '텔레비젼', desc2: '텔리비젼'}, {word: 'fishing', desc: '낚시', desc2: '피싱'},
  {word: 'puppy', desc: '강아지', desc2: '퍼피'},{word: 'sunset', desc: '노을', desc2: '선셋'},{word: 'violin', desc: '바이올린', desc2: '바이올린'},
  {word: 'classroom', desc: '교실', desc2: '클래스룸'},{word: 'book', desc: '책', desc2: '북'},{word: 'clock', desc: '시계', desc2: '클락'},
  {word: 'desk', desc: '책상', desc2: '데스크'},{word: 'door', desc: '문', desc2: '도어'},{word: 'floor', desc: '복도', desc2: '플로어'},
  {word: 'lesson', desc: '수업', desc2: '레슨'},{word: 'chalk', desc: '분필', desc2: '초크'},{word: 'student', desc: '학생', desc2: '스튜던트'},
  {word: 'chair', desc: '의자', desc2: '체어'},{word: 'body', desc: '몸', desc2: '바디'},{word: 'hand', desc: '손', desc2: '핸드'},
  {word: 'arm', desc: '팔', desc2: '암'},{word: 'leg', desc: '다리', desc2: '레그'},{word: 'foot', desc: '발', desc2: '풋'},
  {word: 'face', desc: '얼굴', desc2: '페이스'},{word: 'nose', desc: '코', desc2: '노즈'},{word: 'rice', desc: '쌀', desc2: '라이즈'},
  {word: 'sugar', desc: '설탕', desc2: '슈가'},{word: 'water', desc: '물', desc2: '워터'},{word: 'milk', desc: '우유', desc2: '밀크'},
  {word: 'weather', desc: '날씨', desc2: '웨더'}, {word: 'cold', desc: '추운', desc2: '콜드'},{word: 'warm', desc: '따뜻한', desc2: '웜'},
  {word: 'hot', desc: '더운', desc2: '핫'},{word: 'cool', desc: '추운', desc2: '쿨'},{word: 'jacket', desc: '자켓', desc2: '재킷'},
  {word: 'pants', desc: '바지', desc2: '팬츠'},{word: 'shoes', desc: '신발', desc2: '슈즈'},{word: 'skirt', desc: '치마', desc2: '스커트'},
  {word: 'car', desc: '자동차', desc2: '카'},{word: 'bus', desc: '버스', desc2: '버스'},{word: 'green', desc: '초록색', desc2: '그린'},
  {word: 'yellow', desc: '노란색', desc2: '옐로우'},{word: 'blue', desc: '파란색', desc2: '블루'},{word: 'black', desc: '검은색', desc2: '블랙'},
  {word: 'white', desc: '흰색', desc2: '와이트'},{word: 'nurse', desc: '간호사', desc2: '널스'},{word: 'teacher', desc: '선생님', desc2: '티쳐'},
  {word: 'police', desc: '경찰', desc2: '폴리스'},{word: 'parents', desc: '부모님', desc2: '패런츠'},{word: 'pencil', desc: '연필', desc2: '펜슬'},
  {word: 'snake', desc: '뱀', desc2: '스네이크'}];

export const secondWord = [{word: 'animal', desc: '동물', desc2: '애니멀'}, {word: 'apartment', desc: '아파트', desc2: '아파트먼트'},
  {word: 'airplane', desc: '비행기', desc2: '에어플레인'},{word: 'balloon', desc: '풍선', desc2: '벌룬'}, {word: 'beautiful', desc: '아름다운', desc2: '뷰티플'},
  {word: 'bicycle', desc: '자전거', desc2: '바이서클'}, {word: 'brother', desc: '형제', desc2: '브라더'},
  {word: 'cheese', desc: '치즈', desc2: '치즈'}, {word: 'chopstick', desc: '젓가락', desc2: '찹스틱'}, {word: 'coffee', desc: '커피', desc2: '커피'},
  {word: 'dictionary', desc: '사전', desc2: '딕셔너리'},
  {word: 'dream', desc: '꿈', desc2: '드림'}, {word: 'evening', desc: '저녁, 밤', desc2: '이브닝'},
  {word: 'famous', desc: '유명한', desc2: '패이머스'}, {word: 'floor', desc: '마루, 바닥', desc2: '플로어'},
  {word: 'dolphin', desc: '돌고래', desc2: '돌핀'}, {word: 'hide', desc: '숨다', desc2: '하이드'},
  {word: 'horse', desc: '말', desc2: '호올스'},  {word: 'hospital', desc: '병워', desc2: '하스피털'}, {word: 'hundred', desc: '백, 백의', desc2: '헌드레드'},
  {word: 'friend', desc: '친구', desc2: '프렌드'},  {word: 'fun', desc: '재미', desc2: '펀'},
  {word: 'grandmother', desc: '할머니', desc2: '그랜드마더'}, {word: 'grandfather', desc: '할아버지', desc2: '그랜드파더'},
  {word: 'guitar', desc: '기타', desc2: '기타'}, {word: 'handsome', desc: '잘생긴', desc2: '핸섬'},
  {word: 'finger', desc: '손가락', desc2: '핑거'},{word: 'grandmother', desc: '할머니', desc2: '그랜마더'},{word: 'compass', desc: '나침반', desc2: '컴파스'},
  {word: 'cucumber', desc: '오이', desc2: '큐컴버'},{word: 'dragonfly', desc: '잠자리', desc2: '드래곤플라이'},{word: 'arrow', desc: '화살표', desc2: '애로우'},
  {word: 'wave', desc: '파도', desc2: '웨이브'},{word: 'chicken', desc: '닭', desc2: '치킨'},{word: 'calculator', desc: '계산기', desc2: '칼큘레이터'},
  {word: 'cellphone', desc: '휴대전화', desc2: '셀폰'},{word: 'eraser', desc: '지우개', desc2: '이레이져'},
  {word: 'galaxy', desc: '은하', desc2: '갤럭시'},{word: 'volcano', desc: '화산', desc2: '볼케이노'},{word: 'glacier', desc: '빙하', desc2: '글래시어'},
  {word: 'magnet', desc: '자석', desc2: '마그넷'},{word: 'blackboard', desc: '칠판', desc2: '블랙보드'},
  {word: 'kitchen', desc: '주방', desc2: '키친'},{word: 'vollyball', desc: '배구', desc2: '발리볼'},{word: 'tennis', desc: '테니스', desc2: '테니스'},
  {word: 'soccer', desc: '축구', desc2: '사커'},{word: 'basketball', desc: '농구', desc2: '배스킷볼'},{word: 'baseball', desc: '야구', desc2: '베이스볼'},
  {word: 'hamburger', desc: '햄버거', desc2: '햄버거'}];

export const baseParagraph = [
  {word: 'Boland was a little dinosaur', desc: ''},
  {word: 'He lived with his mother and father', desc: ''},
  {word: 'There ware a lot of dinosaur children', desc: ''},
  {word: 'They played together every day', desc: ''},
  {word: 'His name was Tyrone', desc: ''},
  {word: 'He was just a kid himself', desc: ''},
  {word: 'He was a real bully if you ever saw one', desc: ''},
  {word: 'In fact, he was the world’s first big bully', desc: ''},
  {word: 'Tyrone especially liked to pick on Boland', desc: ''},
  {word: 'He punched amd teased him', desc: ''},
  {word: 'and always stole his snack of sandwich', desc: ''},
  {word: `Boland tried to stay out of Tyrone's way.`, desc: ''},
  {word: 'but it seemed that no matter where he went', desc: ''},
  {word: 'Tyrone was waiting for him', desc: ''},
  {word: 'He kept thinking of ways to avoid Tyrone', desc: ''},
  {word: 'It seemed hopeless', desc: ''},
  {word: `Boland's playmates tried to help`, desc: ''},
  {word: 'You have to get Tyrone to be your friend', desc: ''},
  {word: 'Terry said to Boland one day', desc: ''},
  {word: 'How do you make friends with someone', desc: ''},
  {word: `That's easier sand than done said Boland`, desc: ''},
  {word: 'Boland thought for a while', desc: ''},
  {word: 'What kind of present could he give Tyrone', desc: ''},
  {word: 'A present for Tyrone?', desc: ''},
  {word: `well at least it's worth a try`, desc: ''},
  {word: 'Tyrone looked at Boland for a moment', desc: ''},
  {word: 'Then he smiled a nasty smile', desc: ''},
  {word: 'Ice cream for me? How sweet', desc: ''},
  {word: 'Tyrone grabbed the cone', desc: ''},
  {word: 'Tyrone laughed and walked away', desc: ''},
  {word: 'You are taking this too seriously', desc: ''},
  {word: 'Just stay cool', desc: ''},
  {word: 'He kept on walking', desc: ''},
  {word: `I guess I'll have to help myself again`, desc: ''},
  {word: 'Boland tried not to show his tears', desc: ''},
  {word: 'They were furious', desc: ''},
  {word: 'Tyrone has given you enough trouble', desc: ''},
  {word: 'You can win any fight against him', desc: ''},
  {word: 'Tyrone just has a big mouth', desc: ''}];

export const secondParagraph =[
  {word: 'He was usually called Tyrone the Horrible', desc: ''},
  {word: 'But he was much bigger and stronger than most of the others', desc: ''},
  {word: 'Night after night, Boland had a hard time getting to sleep', desc: ''},
  {word: 'who has been hurting and teasing hyou all your life', desc: ''},
  {word: 'You have to give him a present ahd show him you care', desc: ''},
  {word: 'How Tyrone was always taking his snacks and sandwiches', desc: ''},
  {word: `It's such a hot day, I thought you might like a nice icecream cone`, desc: ''},
  {word: 'Boland could hear Tyrone’s laughter for a long time', desc: ''},
  {word: 'The next day, Boland told his friend Stella what had happened', desc: ''},
  {word: `That's the only thing he'll understand`, desc: ''},
  {word: 'Staying cool when you are scared is not easy', desc: ''},
  {word: `Boland did not play any attention and didn't even try to run away`, desc: ''},
  {word: 'He stomped on Boland’s tail until Boland let go of the sandwich', desc: ''},
  {word: 'You must stand up to him and show him you are a dinosaur too', desc: ''},
  {word: 'And so the next time Boland met Tyrone, he stayed cool', desc: ''},
  {word: `When Boland's friends found out what Tyrone had done`, desc: ''},
  {word: 'Then he turned it upside down and squashed it', desc: ''},
  {word: 'That afternoon Boland went looking for Tyrone', desc: ''},
  {word: `Don't pay any attention to that big bully`, desc: ''}
];
